"client";
import Image from "next/image";
import styles from "./page.module.css";
import Header from "./Components/Header/header";
import Hero from "./Components/Hero/hero";
import Footer from "./Components/Footer/footer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "HOME PAGE",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <>
      <Header />
      <Hero />
      <Footer />
    </>
  );
}
